import os

dir = os.path.dirname(__file__)

addr_withheld = open(os.path.join(dir, 'data/address_withheld.json'), 'r').read()
residence_1 = open(os.path.join(dir, 'data/one_residence.json'), 'r').read()
withheld_flag_fail = open(os.path.join(dir, 'data/residence_withheld_false_no_address.json'), 'r').read()
residence_3_pass = open(os.path.join(dir, 'data/three_residences.json'), 'r').read()
residence_3_fail = open(os.path.join(dir, 'data/three_residences_one_missing_postcode.json'), 'r').read()
no_key_no = open(os.path.join(dir, 'data/no_key_number.json'), 'r').read()
no_ref = open(os.path.join(dir, 'data/no_reference.json'), 'r').read()
no_date = open(os.path.join(dir, 'data/no_date.json'), 'r').read()
no_debtor_name = open(os.path.join(dir, 'data/no_debtor_name.json'), 'r').read()
no_forename = open(os.path.join(dir, 'data/no_debtor_forename.json'), 'r').read()
no_surname = open(os.path.join(dir, 'data/no_debtor_surname.json'), 'r').read()
no_withheld_flag = open(os.path.join(dir, 'data/no_withheld_flag.json'), 'r').read()
forename_2_alt_name = open(os.path.join(dir, 'data/debtor_2_names_alt.json'), 'r').read()
forename_4 = open(os.path.join(dir, 'data/debtor_four_forenames.json'), 'r').read()
no_occupation = open(os.path.join(dir, 'data/no_occupation.json'), 'r').read()
no_trading_name = open(os.path.join(dir, 'data/no_trading_name.json'), 'r').read()
all_fields = open(os.path.join(dir, 'data/all_fields.json'), 'r').read()
